# Generated by Django 5.1.4 on 2024-12-22 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='what_comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reponder',
            new_name='responder',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
