# Generated by Django 5.1.4 on 2024-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_what_comment_reply_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo',
            new_name='image_path',
        ),
        migrations.AddField(
            model_name='listing',
            name='image_URL',
            field=models.URLField(blank=True),
        ),
    ]
