# Generated by Django 5.1.4 on 2024-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_photo_listing_image_path_listing_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='active',
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
