# Generated by Django 5.1.4 on 2024-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_price_bid_current_bid_bid_first_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='first_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
