# Generated by Django 5.1.4 on 2024-12-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_current_bid_alter_bid_first_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_price', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='first_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_price', to='auctions.bid'),
        ),
    ]
