# Generated by Django 5.1.4 on 2024-12-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='current_bid',
            field=models.ManyToManyField(related_name='current_bid', to='auctions.listing'),
        ),
    ]
