# Generated by Django 5.1.4 on 2024-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_creation_date_bid_bid_date_remove_bid_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listing_mages/'),
        ),
    ]
