# Generated by Django 5.1.4 on 2024-12-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_current_bid_bid_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='first_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
