# Generated by Django 5.1.4 on 2024-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_first_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
